
// Objective-C API for talking to the following Go packages
//
//	github.com/bcl-chain/web3.go/mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Web3go_FRAMEWORK_H__
#define __Web3go_FRAMEWORK_H__

#include "Web3go.objc.h"
#include "Universe.objc.h"

#endif
