// Objective-C API for talking to github.com/bcl-chain/web3.go/mobile Go package.
//   gobind -lang=objc github.com/bcl-chain/web3.go/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Web3go_H__
#define __Web3go_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class Web3goAccount;
@class Web3goAccounts;
@class Web3goAddress;
@class Web3goAddresses;
@class Web3goBigFloat;
@class Web3goBigInt;
@class Web3goBigInts;
@class Web3goBlock;
@class Web3goBloom;
@class Web3goBoundContract;
@class Web3goCallMsg;
@class Web3goCallOpts;
@class Web3goContext;
@class Web3goCriteria;
@class Web3goDyToken_;
@class Web3goERC20;
@class Web3goEnode;
@class Web3goEnodes;
@class Web3goEthereumClient;
@class Web3goFilterQuery;
@class Web3goGosHash;
@class Web3goHash;
@class Web3goHashes;
@class Web3goHeader;
@class Web3goHeaders;
@class Web3goHomesteadSigner;
@class Web3goInfo;
@class Web3goInterface;
@class Web3goInterfaces;
@class Web3goKeyStore;
@class Web3goLog;
@class Web3goLogs;
@class Web3goMessage;
@class Web3goMessages;
@class Web3goNewMessage;
@class Web3goNode;
@class Web3goNodeConfig;
@class Web3goNodeInfo;
@class Web3goNonce;
@class Web3goPeerInfo;
@class Web3goPeerInfos;
@class Web3goPrivateKey;
@class Web3goPublicKey;
@class Web3goReceipt;
@class Web3goSigner2;
@class Web3goStrings;
@class Web3goSubscription;
@class Web3goSyncProgress;
@class Web3goTopics;
@class Web3goTransactOpts;
@class Web3goTransaction;
@class Web3goTransactions;
@class Web3goWallet;
@protocol Web3goFilterLogsHandler;
@class Web3goFilterLogsHandler;
@protocol Web3goNewHeadHandler;
@class Web3goNewHeadHandler;
@protocol Web3goSigner;
@class Web3goSigner;

@protocol Web3goFilterLogsHandler <NSObject>
- (void)onError:(NSString* _Nullable)failure;
- (void)onFilterLogs:(Web3goLog* _Nullable)log;
@end

@protocol Web3goNewHeadHandler <NSObject>
- (void)onError:(NSString* _Nullable)failure;
- (void)onNewHead:(Web3goHeader* _Nullable)header;
@end

@protocol Web3goSigner <NSObject>
- (Web3goTransaction* _Nullable)sign:(Web3goAddress* _Nullable)p0 p1:(Web3goTransaction* _Nullable)p1 error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * Account represents a stored key.
 */
@interface Web3goAccount : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * GetAddress retrieves the address associated with the account.
 */
- (Web3goAddress* _Nullable)getAddress;
/**
 * GetURL retrieves the canonical URL of the account.
 */
- (NSString* _Nonnull)getURL;
@end

/**
 * Accounts represents a slice of accounts.
 */
@interface Web3goAccounts : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * Get returns the account at the given index from the slice.
 */
- (Web3goAccount* _Nullable)get:(long)index error:(NSError* _Nullable* _Nullable)error;
/**
 * Set sets the account at the given index in the slice.
 */
- (BOOL)set:(long)index account:(Web3goAccount* _Nullable)account error:(NSError* _Nullable* _Nullable)error;
/**
 * Size returns the number of accounts in the slice.
 */
- (long)size;
@end

/**
 * Address represents the 20 byte address of an Ethereum account.
 */
@interface Web3goAddress : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewAddressFromBytes converts a slice of bytes to a hash value.
 */
- (nullable instancetype)initFromBytes:(NSData* _Nullable)binary;
/**
 * NewAddressFromHex converts a hex string to a address value.
 */
- (nullable instancetype)initFromHex:(NSString* _Nullable)hex;
/**
 * GetBytes retrieves the byte representation of the address.
 */
- (NSData* _Nullable)getBytes;
/**
 * GetHash retrives the Hash representation of the address.
 */
- (Web3goHash* _Nullable)getHash;
/**
 * GetHex retrieves the hex string representation of the address.
 */
- (NSString* _Nonnull)getHex;
/**
 * SetBytes sets the specified slice of bytes as the address value.
 */
- (BOOL)setBytes:(NSData* _Nullable)address error:(NSError* _Nullable* _Nullable)error;
/**
 * SetHex sets the specified hex string as the address value.
 */
- (BOOL)setHex:(NSString* _Nullable)address error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * Addresses represents a slice of addresses.
 */
@interface Web3goAddresses : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewAddresses creates a slice of uninitialized addresses.
 */
- (nullable instancetype)init:(long)size;
/**
 * NewAddressesEmpty creates an empty slice of Addresses values.
 */
- (nullable instancetype)initEmpty;
/**
 * Append adds a new address element to the end of the slice.
 */
- (void)append:(Web3goAddress* _Nullable)address;
/**
 * Get returns the address at the given index from the slice.
 */
- (Web3goAddress* _Nullable)get:(long)index error:(NSError* _Nullable* _Nullable)error;
/**
 * Set sets the address at the given index in the slice.
 */
- (BOOL)set:(long)index address:(Web3goAddress* _Nullable)address error:(NSError* _Nullable* _Nullable)error;
/**
 * Size returns the number of addresses in the slice.
 */
- (long)size;
@end

@interface Web3goBigFloat : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(double)x;
- (Web3goBigInt* _Nullable)getBigInt:(NSError* _Nullable* _Nullable)error;
- (Web3goBigFloat* _Nullable)mul:(Web3goBigFloat* _Nullable)x;
- (NSString* _Nonnull)string;
@end

/**
 * A BigInt represents a signed multi-precision integer.
 */
@interface Web3goBigInt : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewBigInt allocates and returns a new BigInt set to x.
 */
- (nullable instancetype)init:(int64_t)x;
/**
 * GetBytes returns the absolute value of x as a big-endian byte slice.
 */
- (NSData* _Nullable)getBytes;
/**
 * GetInt64 returns the int64 representation of x. If x cannot be represented in
an int64, the result is undefined.
 */
- (int64_t)getInt64;
/**
 * GetString returns the value of x as a formatted string in some number base.
 */
- (NSString* _Nonnull)getString:(long)base;
- (Web3goBigInt* _Nullable)mul:(Web3goBigInt* _Nullable)x;
/**
 * SetBytes interprets buf as the bytes of a big-endian unsigned integer and sets
the big int to that value.
 */
- (void)setBytes:(NSData* _Nullable)buf;
/**
 * SetInt64 sets the big int to x.
 */
- (void)setInt64:(int64_t)x;
/**
 * SetString sets the big int to x.

The string prefix determines the actual conversion base. A prefix of "0x" or
"0X" selects base 16; the "0" prefix selects base 8, and a "0b" or "0B" prefix
selects base 2. Otherwise the selected base is 10.
 */
- (void)setString:(NSString* _Nullable)x base:(long)base;
/**
 * Sign returns:

	-1 if x <  0
	 0 if x == 0
	+1 if x >  0
 */
- (long)sign;
/**
 * String returns the value of x as a formatted decimal string.
 */
- (NSString* _Nonnull)string;
@end

/**
 * BigInts represents a slice of big ints.
 */
@interface Web3goBigInts : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewBigInts creates a slice of uninitialized big numbers.
 */
- (nullable instancetype)init:(long)size;
/**
 * Get returns the bigint at the given index from the slice.
 */
- (Web3goBigInt* _Nullable)get:(long)index error:(NSError* _Nullable* _Nullable)error;
/**
 * Set sets the big int at the given index in the slice.
 */
- (BOOL)set:(long)index bigint:(Web3goBigInt* _Nullable)bigint error:(NSError* _Nullable* _Nullable)error;
/**
 * Size returns the number of big ints in the slice.
 */
- (long)size;
@end

/**
 * Block represents an entire block in the Ethereum blockchain.
 */
@interface Web3goBlock : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewBlockFromJSON parses a block from a JSON data dump.
 */
- (nullable instancetype)initFromJSON:(NSString* _Nullable)data;
/**
 * NewBlockFromRLP parses a block from an RLP data dump.
 */
- (nullable instancetype)initFromRLP:(NSData* _Nullable)data;
/**
 * EncodeJSON encodes a block into a JSON data dump.
 */
- (NSString* _Nonnull)encodeJSON:(NSError* _Nullable* _Nullable)error;
/**
 * EncodeRLP encodes a block into an RLP data dump.
 */
- (NSData* _Nullable)encodeRLP:(NSError* _Nullable* _Nullable)error;
/**
 * GetBloom ...
 */
- (Web3goBloom* _Nullable)getBloom;
/**
 * GetCoinbase ...
 */
- (Web3goAddress* _Nullable)getCoinbase;
/**
 * GetDifficulty ...
 */
- (Web3goBigInt* _Nullable)getDifficulty;
/**
 * GetExtra ...
 */
- (NSData* _Nullable)getExtra;
/**
 * GetGasLimit ...
 */
- (int64_t)getGasLimit;
/**
 * GetGasUsed ...
 */
- (int64_t)getGasUsed;
/**
 * GetHash ...
 */
- (Web3goHash* _Nullable)getHash;
/**
 * GetHeader ...
 */
- (Web3goHeader* _Nullable)getHeader;
/**
 * GetMixDigest ...
 */
- (Web3goHash* _Nullable)getMixDigest;
/**
 * GetNonce ...
 */
- (int64_t)getNonce;
/**
 * GetNumber ...
 */
- (int64_t)getNumber;
/**
 * GetParentHash ...
 */
- (Web3goHash* _Nullable)getParentHash;
/**
 * GetReceiptHash ...
 */
- (Web3goHash* _Nullable)getReceiptHash;
/**
 * GetRoot ...
 */
- (Web3goHash* _Nullable)getRoot;
/**
 * GetTime ...
 */
- (int64_t)getTime;
/**
 * GetTransaction ...
 */
- (Web3goTransaction* _Nullable)getTransaction:(Web3goHash* _Nullable)hash;
/**
 * GetTransactions ...
 */
- (Web3goTransactions* _Nullable)getTransactions;
/**
 * GetTxHash ...
 */
- (Web3goHash* _Nullable)getTxHash;
/**
 * GetUncleHash ...
 */
- (Web3goHash* _Nullable)getUncleHash;
/**
 * GetUncles ...
 */
- (Web3goHeaders* _Nullable)getUncles;
@end

/**
 * Bloom represents a 256 bit bloom filter.
 */
@interface Web3goBloom : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * GetBytes retrieves the byte representation of the bloom filter.
 */
- (NSData* _Nullable)getBytes;
/**
 * GetHex retrieves the hex string representation of the bloom filter.
 */
- (NSString* _Nonnull)getHex;
@end

/**
 * BoundContract is the base wrapper object that reflects a contract on the
Ethereum network. It contains a collection of methods that are used by the
higher level contract bindings to operate.
 */
@interface Web3goBoundContract : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * Call invokes the (constant) contract method with params as input values and
sets the output to result.
 */
- (BOOL)call:(Web3goCallOpts* _Nullable)opts out_:(Web3goInterfaces* _Nullable)out_ method:(NSString* _Nullable)method args:(Web3goInterfaces* _Nullable)args error:(NSError* _Nullable* _Nullable)error;
/**
 * GetAddress ...
 */
- (Web3goAddress* _Nullable)getAddress;
/**
 * GetDeployer ...
 */
- (Web3goTransaction* _Nullable)getDeployer;
/**
 * Transact invokes the (paid) contract method with params as input values.
 */
- (Web3goTransaction* _Nullable)transact:(Web3goTransactOpts* _Nullable)opts method:(NSString* _Nullable)method args:(Web3goInterfaces* _Nullable)args error:(NSError* _Nullable* _Nullable)error;
/**
 * Transfer initiates a plain transaction to move funds to the contract, calling
its default method if one is available.
 */
- (Web3goTransaction* _Nullable)transfer:(Web3goTransactOpts* _Nullable)opts error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * CallMsg contains parameters for contract calls.
 */
@interface Web3goCallMsg : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewCallMsg creates an empty contract call parameter list.
 */
- (nullable instancetype)init;
/**
 * GetData ...
 */
- (NSData* _Nullable)getData;
/**
 * GetFrom ...
 */
- (Web3goAddress* _Nullable)getFrom;
/**
 * GetGas ...
 */
- (int64_t)getGas;
/**
 * GetGasPrice ...
 */
- (Web3goBigInt* _Nullable)getGasPrice;
/**
 * GetTo ...
 */
- (Web3goAddress* _Nullable)getTo;
/**
 * GetValue ...
 */
- (Web3goBigInt* _Nullable)getValue;
/**
 * SetData ...
 */
- (void)setData:(NSData* _Nullable)data;
/**
 * SetFrom ...
 */
- (void)setFrom:(Web3goAddress* _Nullable)address;
/**
 * SetGas ...
 */
- (void)setGas:(int64_t)gas;
/**
 * SetGasPrice ...
 */
- (void)setGasPrice:(Web3goBigInt* _Nullable)price;
/**
 * SetTo ...
 */
- (void)setTo:(Web3goAddress* _Nullable)address;
/**
 * SetValue ...
 */
- (void)setValue:(Web3goBigInt* _Nullable)value;
@end

/**
 * CallOpts is the collection of options to fine tune a contract call request.
 */
@interface Web3goCallOpts : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewCallOpts creates a new option set for contract calls.
 */
- (nullable instancetype)init;
/**
 * GetGasLimit ...
 */
- (int64_t)getGasLimit;
/**
 * IsPending ...
 */
- (BOOL)isPending;
/**
 * SetContext ...
 */
- (void)setContext:(Web3goContext* _Nullable)context;
/**
 * SetGasLimit ...
 */
- (void)setGasLimit:(int64_t)limit;
/**
 * SetPending ...
 */
- (void)setPending:(BOOL)pending;
@end

/**
 * Context carries a deadline, a cancelation signal, and other values across API
boundaries.
 */
@interface Web3goContext : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewContext returns a non-nil, empty Context. It is never canceled, has no
values, and has no deadline. It is typically used by the main function,
initialization, and tests, and as the top-level Context for incoming requests.
 */
- (nullable instancetype)init;
/**
 * WithCancel returns a copy of the original context with cancellation mechanism
included.

Canceling this context releases resources associated with it, so code should
call cancel as soon as the operations running in this Context complete.
 */
- (Web3goContext* _Nullable)withCancel;
/**
 * WithDeadline returns a copy of the original context with the deadline adjusted
to be no later than the specified time.

Canceling this context releases resources associated with it, so code should
call cancel as soon as the operations running in this Context complete.
 */
- (Web3goContext* _Nullable)withDeadline:(int64_t)sec nsec:(int64_t)nsec;
/**
 * WithTimeout returns a copy of the original context with the deadline adjusted
to be no later than now + the duration specified.

Canceling this context releases resources associated with it, so code should
call cancel as soon as the operations running in this Context complete.
 */
- (Web3goContext* _Nullable)withTimeout:(int64_t)nsec;
@end

/**
 * Criteria holds various filter options for inbound messages.
 */
@interface Web3goCriteria : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewCriteria ...
 */
- (nullable instancetype)init:(NSData* _Nullable)topic;
/**
 * GetMinPow ...
 */
- (double)getMinPow;
/**
 * GetPrivateKeyID ...
 */
- (NSString* _Nonnull)getPrivateKeyID;
/**
 * GetSig ...
 */
- (NSData* _Nullable)getSig;
/**
 * GetSymKeyID ...
 */
- (NSString* _Nonnull)getSymKeyID;
/**
 * SetMinPow ...
 */
- (void)setMinPow:(double)pow;
/**
 * SetPrivateKeyID ...
 */
- (void)setPrivateKeyID:(NSString* _Nullable)privateKeyID;
/**
 * SetSig ...
 */
- (void)setSig:(NSData* _Nullable)sig;
/**
 * SetSymKeyID ...
 */
- (void)setSymKeyID:(NSString* _Nullable)symKeyID;
@end

@interface Web3goDyToken_ : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field DyToken_.DyToken with unsupported type: *github.com/bcl-chain/web3.go/contract/dytoken.DyToken

- (Web3goBigInt* _Nullable)balanceOf:(Web3goAddress* _Nullable)who error:(NSError* _Nullable* _Nullable)error;
- (Web3goTransaction* _Nullable)buildBurn:(Web3goTransactOpts* _Nullable)opts value:(Web3goBigInt* _Nullable)value error:(NSError* _Nullable* _Nullable)error;
- (Web3goTransaction* _Nullable)buildMint:(Web3goTransactOpts* _Nullable)opts to:(Web3goAddress* _Nullable)to value:(Web3goBigInt* _Nullable)value error:(NSError* _Nullable* _Nullable)error;
- (Web3goTransaction* _Nullable)buildPause:(Web3goTransactOpts* _Nullable)opts error:(NSError* _Nullable* _Nullable)error;
- (Web3goTransaction* _Nullable)buildTransfer:(Web3goTransactOpts* _Nullable)opts to:(Web3goAddress* _Nullable)to value:(Web3goBigInt* _Nullable)value error:(NSError* _Nullable* _Nullable)error;
- (Web3goTransaction* _Nullable)buildTransferGRCOwnership:(Web3goTransactOpts* _Nullable)opts to:(Web3goAddress* _Nullable)to error:(NSError* _Nullable* _Nullable)error;
- (Web3goTransaction* _Nullable)buildUnPause:(Web3goTransactOpts* _Nullable)opts error:(NSError* _Nullable* _Nullable)error;
/**
 * 销毁功能
burn function
 */
- (Web3goTransaction* _Nullable)burn:(Web3goTransactOpts* _Nullable)opts value:(Web3goBigInt* _Nullable)value error:(NSError* _Nullable* _Nullable)error;
/**
 * 判断是否有增发权限
if someone has the right to mint
 */
- (BOOL)isMinter:(Web3goAddress* _Nullable)to ret0_:(BOOL* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
/**
 * 判断是否有禁用权限
if someone has the right to pause
 */
- (BOOL)isPauser:(Web3goAddress* _Nullable)to ret0_:(BOOL* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
/**
 * 增发功能
mint function
 */
- (Web3goTransaction* _Nullable)mint:(Web3goTransactOpts* _Nullable)opts to:(Web3goAddress* _Nullable)to value:(Web3goBigInt* _Nullable)value error:(NSError* _Nullable* _Nullable)error;
/**
 * 禁用功能
pause function
 */
- (Web3goTransaction* _Nullable)pause:(Web3goTransactOpts* _Nullable)opts error:(NSError* _Nullable* _Nullable)error;
/**
 * 是否被禁用
if it is paused
 */
- (BOOL)paused:(BOOL* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
/**
 * 把交易发送到网络签名
send txs to net to sign
 */
- (Web3goTransaction* _Nullable)transfer:(Web3goTransactOpts* _Nullable)opts to:(Web3goAddress* _Nullable)to value:(Web3goBigInt* _Nullable)value error:(NSError* _Nullable* _Nullable)error;
/**
 * 转移权限功能
transfer token's ownership
 */
- (Web3goTransaction* _Nullable)transferGRCOwnership:(Web3goTransactOpts* _Nullable)opts to:(Web3goAddress* _Nullable)to error:(NSError* _Nullable* _Nullable)error;
/**
 * 启用功能
unpause function
 */
- (Web3goTransaction* _Nullable)unPause:(Web3goTransactOpts* _Nullable)opts error:(NSError* _Nullable* _Nullable)error;
@end

@interface Web3goERC20 : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * 封装erc20
 */
- (nullable instancetype)init:(Web3goAddress* _Nullable)address client:(Web3goEthereumClient* _Nullable)client;
- (Web3goBigInt* _Nullable)balanceOf:(Web3goAddress* _Nullable)who error:(NSError* _Nullable* _Nullable)error;
- (Web3goTransaction* _Nullable)buildTransfer:(Web3goTransactOpts* _Nullable)opts to:(Web3goAddress* _Nullable)to value:(Web3goBigInt* _Nullable)value error:(NSError* _Nullable* _Nullable)error;
- (Web3goTransaction* _Nullable)transfer:(Web3goTransactOpts* _Nullable)opts to:(Web3goAddress* _Nullable)to value:(Web3goBigInt* _Nullable)value error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * Enode represents a host on the network.
 */
@interface Web3goEnode : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewEnode parses a node designator.

There are two basic forms of node designators
  - incomplete nodes, which only have the public key (node ID)
  - complete nodes, which contain the public key and IP/Port information

For incomplete nodes, the designator must look like one of these

   enode://<hex node id>
   <hex node id>

For complete nodes, the node ID is encoded in the username portion
of the URL, separated from the host by an @ sign. The hostname can
only be given as an IP address, DNS domain names are not allowed.
The port in the host name section is the TCP listening port. If the
TCP and UDP (discovery) ports differ, the UDP port is specified as
query parameter "discport".

In the following example, the node URL describes
a node with IP address 10.3.58.6, TCP listening port 30303
and UDP discovery port 30301.

   enode://<hex node id>@10.3.58.6:30303?discport=30301
 */
- (nullable instancetype)init:(NSString* _Nullable)rawurl;
@end

/**
 * Enodes represents a slice of accounts.
 */
@interface Web3goEnodes : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewEnodes creates a slice of uninitialized enodes.
 */
- (nullable instancetype)init:(long)size;
/**
 * NewEnodesEmpty creates an empty slice of Enode values.
 */
- (nullable instancetype)initEmpty;
/**
 * Append adds a new enode element to the end of the slice.
 */
- (void)append:(Web3goEnode* _Nullable)enode;
/**
 * Get returns the enode at the given index from the slice.
 */
- (Web3goEnode* _Nullable)get:(long)index error:(NSError* _Nullable* _Nullable)error;
/**
 * Set sets the enode at the given index in the slice.
 */
- (BOOL)set:(long)index enode:(Web3goEnode* _Nullable)enode error:(NSError* _Nullable* _Nullable)error;
/**
 * Size returns the number of enodes in the slice.
 */
- (long)size;
@end

/**
 * EthereumClient provides access to the Ethereum APIs.
 */
@interface Web3goEthereumClient : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewEthereumClient connects a client to the given URL.
 */
- (nullable instancetype)init:(NSString* _Nullable)rawurl;
/**
 * CallContract executes a message call transaction, which is directly executed in the VM
of the node, but never mined into the blockchain.

blockNumber selects the block height at which the call runs. It can be <0, in which
case the code is taken from the latest known block. Note that state from very old
blocks might not be available.
 */
- (NSData* _Nullable)callContract:(Web3goContext* _Nullable)ctx msg:(Web3goCallMsg* _Nullable)msg number:(int64_t)number error:(NSError* _Nullable* _Nullable)error;
/**
 * EstimateGas tries to estimate the gas needed to execute a specific transaction based on
the current pending state of the backend blockchain. There is no guarantee that this is
the true gas limit requirement as other transactions may be added or removed by miners,
but it should provide a basis for setting a reasonable default.
 */
- (BOOL)estimateGas:(Web3goContext* _Nullable)ctx msg:(Web3goCallMsg* _Nullable)msg gas:(int64_t* _Nullable)gas error:(NSError* _Nullable* _Nullable)error;
/**
 * FilterLogs executes a filter query.
 */
- (Web3goLogs* _Nullable)filterLogs:(Web3goContext* _Nullable)ctx query:(Web3goFilterQuery* _Nullable)query error:(NSError* _Nullable* _Nullable)error;
/**
 * GetBalanceAt returns the wei balance of the given account.
The block number can be <0, in which case the balance is taken from the latest known block.
 */
- (Web3goBigInt* _Nullable)getBalanceAt:(Web3goContext* _Nullable)ctx account:(Web3goAddress* _Nullable)account number:(int64_t)number error:(NSError* _Nullable* _Nullable)error;
/**
 * GetBlockByHash returns the given full block.
 */
- (Web3goBlock* _Nullable)getBlockByHash:(Web3goContext* _Nullable)ctx hash:(Web3goHash* _Nullable)hash error:(NSError* _Nullable* _Nullable)error;
/**
 * GetBlockByNumber returns a block from the current canonical chain. If number is <0, the
latest known block is returned.
 */
- (Web3goBlock* _Nullable)getBlockByNumber:(Web3goContext* _Nullable)ctx number:(int64_t)number error:(NSError* _Nullable* _Nullable)error;
/**
 * GetCodeAt returns the contract code of the given account.
The block number can be <0, in which case the code is taken from the latest known block.
 */
- (NSData* _Nullable)getCodeAt:(Web3goContext* _Nullable)ctx account:(Web3goAddress* _Nullable)account number:(int64_t)number error:(NSError* _Nullable* _Nullable)error;
/**
 * GetHeaderByHash returns the block header with the given hash.
 */
- (Web3goHeader* _Nullable)getHeaderByHash:(Web3goContext* _Nullable)ctx hash:(Web3goHash* _Nullable)hash error:(NSError* _Nullable* _Nullable)error;
/**
 * GetHeaderByNumber returns a block header from the current canonical chain. If number is <0,
the latest known header is returned.
 */
- (Web3goHeader* _Nullable)getHeaderByNumber:(Web3goContext* _Nullable)ctx number:(int64_t)number error:(NSError* _Nullable* _Nullable)error;
/**
 * GetNonceAt returns the account nonce of the given account.
The block number can be <0, in which case the nonce is taken from the latest known block.
 */
- (BOOL)getNonceAt:(Web3goContext* _Nullable)ctx account:(Web3goAddress* _Nullable)account number:(int64_t)number nonce:(int64_t* _Nullable)nonce error:(NSError* _Nullable* _Nullable)error;
/**
 * GetPendingBalanceAt returns the wei balance of the given account in the pending state.
 */
- (Web3goBigInt* _Nullable)getPendingBalanceAt:(Web3goContext* _Nullable)ctx account:(Web3goAddress* _Nullable)account error:(NSError* _Nullable* _Nullable)error;
/**
 * GetPendingCodeAt returns the contract code of the given account in the pending state.
 */
- (NSData* _Nullable)getPendingCodeAt:(Web3goContext* _Nullable)ctx account:(Web3goAddress* _Nullable)account error:(NSError* _Nullable* _Nullable)error;
/**
 * GetPendingNonceAt returns the account nonce of the given account in the pending state.
This is the nonce that should be used for the next transaction.
 */
- (BOOL)getPendingNonceAt:(Web3goContext* _Nullable)ctx account:(Web3goAddress* _Nullable)account nonce:(int64_t* _Nullable)nonce error:(NSError* _Nullable* _Nullable)error;
/**
 * GetPendingStorageAt returns the value of key in the contract storage of the given account in the pending state.
 */
- (NSData* _Nullable)getPendingStorageAt:(Web3goContext* _Nullable)ctx account:(Web3goAddress* _Nullable)account key:(Web3goHash* _Nullable)key error:(NSError* _Nullable* _Nullable)error;
/**
 * GetPendingTransactionCount returns the total number of transactions in the pending state.
 */
- (BOOL)getPendingTransactionCount:(Web3goContext* _Nullable)ctx count:(long* _Nullable)count error:(NSError* _Nullable* _Nullable)error;
/**
 * GetStorageAt returns the value of key in the contract storage of the given account.
The block number can be <0, in which case the value is taken from the latest known block.
 */
- (NSData* _Nullable)getStorageAt:(Web3goContext* _Nullable)ctx account:(Web3goAddress* _Nullable)account key:(Web3goHash* _Nullable)key number:(int64_t)number error:(NSError* _Nullable* _Nullable)error;
/**
 * GetTransactionByHash returns the transaction with the given hash.
 */
- (Web3goTransaction* _Nullable)getTransactionByHash:(Web3goContext* _Nullable)ctx hash:(Web3goHash* _Nullable)hash error:(NSError* _Nullable* _Nullable)error;
/**
 * GetTransactionByHashIsPending returns if the transaction pending or not.
 */
- (BOOL)getTransactionByHashIsPending:(Web3goContext* _Nullable)ctx hash:(Web3goHash* _Nullable)hash ret0_:(BOOL* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
/**
 * GetTransactionCount returns the total number of transactions in the given block.
 */
- (BOOL)getTransactionCount:(Web3goContext* _Nullable)ctx hash:(Web3goHash* _Nullable)hash count:(long* _Nullable)count error:(NSError* _Nullable* _Nullable)error;
/**
 * GetTransactionInBlock returns a single transaction at index in the given block.
 */
- (Web3goTransaction* _Nullable)getTransactionInBlock:(Web3goContext* _Nullable)ctx hash:(Web3goHash* _Nullable)hash index:(long)index error:(NSError* _Nullable* _Nullable)error;
/**
 * GetTransactionReceipt returns the receipt of a transaction by transaction hash.
Note that the receipt is not available for pending transactions.
 */
- (Web3goReceipt* _Nullable)getTransactionReceipt:(Web3goContext* _Nullable)ctx hash:(Web3goHash* _Nullable)hash error:(NSError* _Nullable* _Nullable)error;
/**
 * GetTransactionSender returns the sender address of a transaction. The transaction must
be included in blockchain at the given block and index.
 */
- (Web3goAddress* _Nullable)getTransactionSender:(Web3goContext* _Nullable)ctx tx:(Web3goTransaction* _Nullable)tx blockhash:(Web3goHash* _Nullable)blockhash index:(long)index error:(NSError* _Nullable* _Nullable)error;
/**
 * PendingCallContract executes a message call transaction using the EVM.
The state seen by the contract call is the pending state.
 */
- (NSData* _Nullable)pendingCallContract:(Web3goContext* _Nullable)ctx msg:(Web3goCallMsg* _Nullable)msg error:(NSError* _Nullable* _Nullable)error;
/**
 * SendTransaction injects a signed transaction into the pending pool for execution.

If the transaction was a contract creation use the TransactionReceipt method to get the
contract address after the transaction has been mined.
 */
- (BOOL)sendTransaction:(Web3goContext* _Nullable)ctx tx:(Web3goTransaction* _Nullable)tx error:(NSError* _Nullable* _Nullable)error;
/**
 * SubscribeFilterLogs subscribes to the results of a streaming filter query.
 */
- (Web3goSubscription* _Nullable)subscribeFilterLogs:(Web3goContext* _Nullable)ctx query:(Web3goFilterQuery* _Nullable)query handler:(id<Web3goFilterLogsHandler> _Nullable)handler buffer:(long)buffer error:(NSError* _Nullable* _Nullable)error;
/**
 * SubscribeNewHead subscribes to notifications about the current blockchain head
on the given channel.
 */
- (Web3goSubscription* _Nullable)subscribeNewHead:(Web3goContext* _Nullable)ctx handler:(id<Web3goNewHeadHandler> _Nullable)handler buffer:(long)buffer error:(NSError* _Nullable* _Nullable)error;
/**
 * SuggestGasPrice retrieves the currently suggested gas price to allow a timely
execution of a transaction.
 */
- (Web3goBigInt* _Nullable)suggestGasPrice:(Web3goContext* _Nullable)ctx error:(NSError* _Nullable* _Nullable)error;
/**
 * SyncProgress retrieves the current progress of the sync algorithm. If there's
no sync currently running, it returns nil.
 */
- (Web3goSyncProgress* _Nullable)syncProgress:(Web3goContext* _Nullable)ctx error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * FilterQuery contains options for contract log filtering.
 */
@interface Web3goFilterQuery : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewFilterQuery creates an empty filter query for contract log filtering.
 */
- (nullable instancetype)init;
/**
 * GetAddresses ...
 */
- (Web3goAddresses* _Nullable)getAddresses;
/**
 * GetFromBlock ...
 */
- (Web3goBigInt* _Nullable)getFromBlock;
/**
 * GetToBlock ...
 */
- (Web3goBigInt* _Nullable)getToBlock;
/**
 * GetTopics ...
 */
- (Web3goTopics* _Nullable)getTopics;
/**
 * SetAddresses ...
 */
- (void)setAddresses:(Web3goAddresses* _Nullable)addresses;
/**
 * SetFromBlock ...
 */
- (void)setFromBlock:(Web3goBigInt* _Nullable)fromBlock;
/**
 * SetToBlock ...
 */
- (void)setToBlock:(Web3goBigInt* _Nullable)toBlock;
/**
 * SetTopics ...
 */
- (void)setTopics:(Web3goTopics* _Nullable)topics;
@end

/**
 * GosHash ...
 */
@interface Web3goGosHash : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * Size ...
 */
- (long)size;
/**
 * Sum ...
 */
- (NSData* _Nullable)sum:(NSData* _Nullable)b;
/**
 * Write ...
 */
- (BOOL)write:(NSData* _Nullable)p0 ret0_:(long* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * Hash represents the 32 byte Keccak256 hash of arbitrary data.
 */
@interface Web3goHash : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewHashFromBytes converts a slice of bytes to a hash value.
 */
- (nullable instancetype)initFromBytes:(NSData* _Nullable)binary;
/**
 * NewHashFromHex converts a hex string to a hash value.
 */
- (nullable instancetype)initFromHex:(NSString* _Nullable)hex;
/**
 * GetBytes retrieves the byte representation of the hash.
 */
- (NSData* _Nullable)getBytes;
/**
 * GetHex retrieves the hex string representation of the hash.
 */
- (NSString* _Nonnull)getHex;
/**
 * SetBytes sets the specified slice of bytes as the hash value.
 */
- (BOOL)setBytes:(NSData* _Nullable)hash error:(NSError* _Nullable* _Nullable)error;
/**
 * SetHex sets the specified hex string as the hash value.
 */
- (BOOL)setHex:(NSString* _Nullable)hash error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * Hashes represents a slice of hashes.
 */
@interface Web3goHashes : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewHashes creates a slice of uninitialized Hashes.
 */
- (nullable instancetype)init:(long)size;
/**
 * NewHashesEmpty creates an empty slice of Hashes values.
 */
- (nullable instancetype)initEmpty;
/**
 * Append adds a new Hash element to the end of the slice.
 */
- (void)append:(Web3goHash* _Nullable)hash;
/**
 * Get returns the hash at the given index from the slice.
 */
- (Web3goHash* _Nullable)get:(long)index error:(NSError* _Nullable* _Nullable)error;
/**
 * Set sets the Hash at the given index in the slice.
 */
- (BOOL)set:(long)index hash:(Web3goHash* _Nullable)hash error:(NSError* _Nullable* _Nullable)error;
/**
 * Size returns the number of hashes in the slice.
 */
- (long)size;
@end

/**
 * Header represents a block header in the Ethereum blockchain.
 */
@interface Web3goHeader : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewHeaderFromJSON parses a header from a JSON data dump.
 */
- (nullable instancetype)initFromJSON:(NSString* _Nullable)data;
/**
 * NewHeaderFromRLP parses a header from an RLP data dump.
 */
- (nullable instancetype)initFromRLP:(NSData* _Nullable)data;
/**
 * EncodeJSON encodes a header into a JSON data dump.
 */
- (NSString* _Nonnull)encodeJSON:(NSError* _Nullable* _Nullable)error;
/**
 * EncodeRLP encodes a header into an RLP data dump.
 */
- (NSData* _Nullable)encodeRLP:(NSError* _Nullable* _Nullable)error;
/**
 * GetBloom ...
 */
- (Web3goBloom* _Nullable)getBloom;
/**
 * GetCoinbase ...
 */
- (Web3goAddress* _Nullable)getCoinbase;
/**
 * GetDifficulty ...
 */
- (Web3goBigInt* _Nullable)getDifficulty;
/**
 * GetExtra ...
 */
- (NSData* _Nullable)getExtra;
/**
 * GetGasLimit ...
 */
- (int64_t)getGasLimit;
/**
 * GetGasUsed ...
 */
- (int64_t)getGasUsed;
/**
 * GetHash ...
 */
- (Web3goHash* _Nullable)getHash;
/**
 * GetMixDigest ...
 */
- (Web3goHash* _Nullable)getMixDigest;
/**
 * GetNonce ...
 */
- (Web3goNonce* _Nullable)getNonce;
/**
 * GetNumber ...
 */
- (int64_t)getNumber;
/**
 * GetParentHash ...
 */
- (Web3goHash* _Nullable)getParentHash;
/**
 * GetReceiptHash ...
 */
- (Web3goHash* _Nullable)getReceiptHash;
/**
 * GetRoot ...
 */
- (Web3goHash* _Nullable)getRoot;
/**
 * GetTime ...
 */
- (int64_t)getTime;
/**
 * GetTxHash ...
 */
- (Web3goHash* _Nullable)getTxHash;
/**
 * GetUncleHash ...
 */
- (Web3goHash* _Nullable)getUncleHash;
@end

/**
 * Headers represents a slice of headers.
 */
@interface Web3goHeaders : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * Get returns the header at the given index from the slice.
 */
- (Web3goHeader* _Nullable)get:(long)index error:(NSError* _Nullable* _Nullable)error;
/**
 * Size returns the number of headers in the slice.
 */
- (long)size;
@end

/**
 * HomesteadSigner ...
 */
@interface Web3goHomesteadSigner : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@end

/**
 * Info represents a diagnostic information about the whisper node.
 */
@interface Web3goInfo : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@end

/**
 * Interface represents a wrapped version of Go's interface{}, with the capacity
to store arbitrary data types.

Since it's impossible to get the arbitrary-ness converted between Go and mobile
platforms, we're using explicit getters and setters for the conversions. There
is of course no point in enumerating everything, just enough to support the
contract bindins requiring client side generated code.
 */
@interface Web3goInterface : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewInterface creates a new empty interface that can be used to pass around
generic types.
 */
- (nullable instancetype)init;
/**
 * GetAddress ...
 */
- (Web3goAddress* _Nullable)getAddress;
/**
 * GetAddresses ...
 */
- (Web3goAddresses* _Nullable)getAddresses;
/**
 * GetBigInt ...
 */
- (Web3goBigInt* _Nullable)getBigInt;
/**
 * GetBigInts ...
 */
- (Web3goBigInts* _Nullable)getBigInts;
/**
 * GetBinary ...
 */
- (NSData* _Nullable)getBinary;
/**
 * GetBool ...
 */
- (BOOL)getBool;
/**
 * GetHash ...
 */
- (Web3goHash* _Nullable)getHash;
/**
 * GetHashes ...
 */
- (Web3goHashes* _Nullable)getHashes;
/**
 * GetInt16 ...
 */
- (int16_t)getInt16;
/**
 * GetInt32 ...
 */
- (int32_t)getInt32;
/**
 * GetInt64 ...
 */
- (int64_t)getInt64;
/**
 * GetInt8 ...
 */
- (int8_t)getInt8;
/**
 * GetString ...
 */
- (NSString* _Nonnull)getString;
/**
 * GetStrings ...
 */
- (Web3goStrings* _Nullable)getStrings;
/**
 * GetUint16 ...
 */
- (Web3goBigInt* _Nullable)getUint16;
/**
 * GetUint32 ...
 */
- (Web3goBigInt* _Nullable)getUint32;
/**
 * GetUint64 ...
 */
- (Web3goBigInt* _Nullable)getUint64;
/**
 * GetUint8 ...
 */
- (Web3goBigInt* _Nullable)getUint8;
/**
 * SetAddress ...
 */
- (void)setAddress:(Web3goAddress* _Nullable)address;
/**
 * SetAddresses ...
 */
- (void)setAddresses:(Web3goAddresses* _Nullable)addrs;
/**
 * SetBigInt ...
 */
- (void)setBigInt:(Web3goBigInt* _Nullable)bigint;
/**
 * SetBigInts ...
 */
- (void)setBigInts:(Web3goBigInts* _Nullable)bigints;
/**
 * SetBinary ...
 */
- (void)setBinary:(NSData* _Nullable)binary;
/**
 * SetBool ...
 */
- (void)setBool:(BOOL)b;
/**
 * SetDefaultAddress ...
 */
- (void)setDefaultAddress;
/**
 * SetDefaultAddresses ...
 */
- (void)setDefaultAddresses;
/**
 * SetDefaultBigInt ...
 */
- (void)setDefaultBigInt;
/**
 * SetDefaultBigInts ...
 */
- (void)setDefaultBigInts;
/**
 * SetDefaultBinaries ...
 */
- (void)setDefaultBinaries;
/**
 * SetDefaultBinary ...
 */
- (void)setDefaultBinary;
/**
 * SetDefaultBool ...
 */
- (void)setDefaultBool;
/**
 * SetDefaultBools ...
 */
- (void)setDefaultBools;
/**
 * SetDefaultHash ...
 */
- (void)setDefaultHash;
/**
 * SetDefaultHashes ...
 */
- (void)setDefaultHashes;
/**
 * SetDefaultInt16 ...
 */
- (void)setDefaultInt16;
/**
 * SetDefaultInt32 ...
 */
- (void)setDefaultInt32;
/**
 * SetDefaultInt64 ...
 */
- (void)setDefaultInt64;
/**
 * SetDefaultInt8 ...
 */
- (void)setDefaultInt8;
/**
 * SetDefaultString ...
 */
- (void)setDefaultString;
/**
 * SetDefaultStrings ...
 */
- (void)setDefaultStrings;
/**
 * SetDefaultUint16 ...
 */
- (void)setDefaultUint16;
/**
 * SetDefaultUint32 ...
 */
- (void)setDefaultUint32;
/**
 * SetDefaultUint64 ...
 */
- (void)setDefaultUint64;
/**
 * SetDefaultUint8 ...
 */
- (void)setDefaultUint8;
/**
 * SetHash ...
 */
- (void)setHash:(Web3goHash* _Nullable)hash;
/**
 * SetHashes ...
 */
- (void)setHashes:(Web3goHashes* _Nullable)hashes;
/**
 * SetInt16 ...
 */
- (void)setInt16:(int16_t)n;
/**
 * SetInt32 ...
 */
- (void)setInt32:(int32_t)n;
/**
 * SetInt64 ...
 */
- (void)setInt64:(int64_t)n;
/**
 * SetInt8 ...
 */
- (void)setInt8:(int8_t)n;
/**
 * SetString ...
 */
- (void)setString:(NSString* _Nullable)str;
/**
 * SetStrings ...
 */
- (void)setStrings:(Web3goStrings* _Nullable)strs;
/**
 * SetUint16 ...
 */
- (void)setUint16:(Web3goBigInt* _Nullable)bigint;
/**
 * SetUint32 ...
 */
- (void)setUint32:(Web3goBigInt* _Nullable)bigint;
/**
 * SetUint64 ...
 */
- (void)setUint64:(Web3goBigInt* _Nullable)bigint;
/**
 * SetUint8 ...
 */
- (void)setUint8:(Web3goBigInt* _Nullable)bigint;
@end

/**
 * Interfaces is a slices of wrapped generic objects.
 */
@interface Web3goInterfaces : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewInterfaces creates a slice of uninitialized interfaces.
 */
- (nullable instancetype)init:(long)size;
/**
 * Get returns the bigint at the given index from the slice.
 */
- (Web3goInterface* _Nullable)get:(long)index error:(NSError* _Nullable* _Nullable)error;
/**
 * Set sets the big int at the given index in the slice.
 */
- (BOOL)set:(long)index object:(Web3goInterface* _Nullable)object error:(NSError* _Nullable* _Nullable)error;
/**
 * Size returns the number of interfaces in the slice.
 */
- (long)size;
@end

/**
 * KeyStore manages a key storage directory on disk.
 */
@interface Web3goKeyStore : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewKeyStore creates a keystore for the given directory.
 */
- (nullable instancetype)init:(NSString* _Nullable)keydir scryptN:(long)scryptN scryptP:(long)scryptP;
/**
 * DeleteAccount deletes the key matched by account if the passphrase is correct.
If a contains no filename, the address must match a unique key.
 */
- (BOOL)deleteAccount:(Web3goAccount* _Nullable)account passphrase:(NSString* _Nullable)passphrase error:(NSError* _Nullable* _Nullable)error;
/**
 * ExportKey exports as a JSON key, encrypted with newPassphrase.
 */
- (NSData* _Nullable)exportKey:(Web3goAccount* _Nullable)account passphrase:(NSString* _Nullable)passphrase newPassphrase:(NSString* _Nullable)newPassphrase error:(NSError* _Nullable* _Nullable)error;
/**
 * GetAccounts returns all key files present in the directory.
 */
- (Web3goAccounts* _Nullable)getAccounts;
/**
 * HasAddress reports whether a key with the given address is present.
 */
- (BOOL)hasAddress:(Web3goAddress* _Nullable)address;
/**
 * ImportECDSAKey stores the given encrypted JSON key into the key directory.
 */
- (Web3goAccount* _Nullable)importECDSAKey:(NSData* _Nullable)key passphrase:(NSString* _Nullable)passphrase error:(NSError* _Nullable* _Nullable)error;
/**
 * ImportKey stores the given encrypted JSON key into the key directory.
 */
- (Web3goAccount* _Nullable)importKey:(NSData* _Nullable)keyJSON passphrase:(NSString* _Nullable)passphrase newPassphrase:(NSString* _Nullable)newPassphrase error:(NSError* _Nullable* _Nullable)error;
/**
 * ImportPreSaleKey decrypts the given Ethereum presale wallet and stores
a key file in the key directory. The key file is encrypted with the same passphrase.
 */
- (Web3goAccount* _Nullable)importPreSaleKey:(NSData* _Nullable)keyJSON passphrase:(NSString* _Nullable)passphrase error:(NSError* _Nullable* _Nullable)error;
/**
 * Lock removes the private key with the given address from memory.
 */
- (BOOL)lock:(Web3goAddress* _Nullable)address error:(NSError* _Nullable* _Nullable)error;
/**
 * NewAccount generates a new key and stores it into the key directory,
encrypting it with the passphrase.
 */
- (Web3goAccount* _Nullable)newAccount:(NSString* _Nullable)passphrase error:(NSError* _Nullable* _Nullable)error;
/**
 * SignHash calculates a ECDSA signature for the given hash. The produced signature
is in the [R || S || V] format where V is 0 or 1.
 */
- (NSData* _Nullable)signHash:(Web3goAddress* _Nullable)address hash:(NSData* _Nullable)hash error:(NSError* _Nullable* _Nullable)error;
/**
 * SignHashPassphrase signs hash if the private key matching the given address can
be decrypted with the given passphrase. The produced signature is in the
[R || S || V] format where V is 0 or 1.
 */
- (NSData* _Nullable)signHashPassphrase:(Web3goAccount* _Nullable)account passphrase:(NSString* _Nullable)passphrase hash:(NSData* _Nullable)hash error:(NSError* _Nullable* _Nullable)error;
/**
 * SignTx signs the given transaction with the requested account.
 */
- (Web3goTransaction* _Nullable)signTx:(Web3goAccount* _Nullable)account tx:(Web3goTransaction* _Nullable)tx chainID:(Web3goBigInt* _Nullable)chainID error:(NSError* _Nullable* _Nullable)error;
/**
 * SignTxPassphrase signs the transaction if the private key matching the
given address can be decrypted with the given passphrase.
 */
- (Web3goTransaction* _Nullable)signTxPassphrase:(Web3goAccount* _Nullable)account passphrase:(NSString* _Nullable)passphrase tx:(Web3goTransaction* _Nullable)tx chainID:(Web3goBigInt* _Nullable)chainID error:(NSError* _Nullable* _Nullable)error;
/**
 * TimedUnlock unlocks the given account with the passphrase. The account stays
unlocked for the duration of timeout (nanoseconds). A timeout of 0 unlocks the
account until the program exits. The account must match a unique key file.

If the account address is already unlocked for a duration, TimedUnlock extends or
shortens the active unlock timeout. If the address was previously unlocked
indefinitely the timeout is not altered.
 */
- (BOOL)timedUnlock:(Web3goAccount* _Nullable)account passphrase:(NSString* _Nullable)passphrase timeout:(int64_t)timeout error:(NSError* _Nullable* _Nullable)error;
/**
 * Unlock unlocks the given account indefinitely.
 */
- (BOOL)unlock:(Web3goAccount* _Nullable)account passphrase:(NSString* _Nullable)passphrase error:(NSError* _Nullable* _Nullable)error;
/**
 * UpdateAccount changes the passphrase of an existing account.
 */
- (BOOL)updateAccount:(Web3goAccount* _Nullable)account passphrase:(NSString* _Nullable)passphrase newPassphrase:(NSString* _Nullable)newPassphrase error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * Log represents a contract log event. These events are generated by the LOG
opcode and stored/indexed by the node.
 */
@interface Web3goLog : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * GetAddress ...
 */
- (Web3goAddress* _Nullable)getAddress;
/**
 * GetBlockHash ...
 */
- (Web3goHash* _Nullable)getBlockHash;
/**
 * GetBlockNumber ...
 */
- (int64_t)getBlockNumber;
/**
 * GetData ...
 */
- (NSData* _Nullable)getData;
/**
 * GetIndex ...
 */
- (long)getIndex;
/**
 * GetTopics ...
 */
- (Web3goHashes* _Nullable)getTopics;
/**
 * GetTxHash ...
 */
- (Web3goHash* _Nullable)getTxHash;
/**
 * GetTxIndex ...
 */
- (long)getTxIndex;
@end

/**
 * Logs represents a slice of VM logs.
 */
@interface Web3goLogs : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * Get returns the log at the given index from the slice.
 */
- (Web3goLog* _Nullable)get:(long)index error:(NSError* _Nullable* _Nullable)error;
/**
 * Size returns the number of logs in the slice.
 */
- (long)size;
@end

/**
 * Message represents a whisper message.
 */
@interface Web3goMessage : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * GetDst ...
 */
- (NSData* _Nullable)getDst;
/**
 * GetHash ...
 */
- (NSData* _Nullable)getHash;
/**
 * GetPayload ...
 */
- (NSData* _Nullable)getPayload;
/**
 * GetPoW ...
 */
- (double)getPoW;
/**
 * GetSig ...
 */
- (NSData* _Nullable)getSig;
/**
 * GetTTL ...
 */
- (int64_t)getTTL;
/**
 * GetTimestamp ...
 */
- (int64_t)getTimestamp;
@end

/**
 * Messages represents an array of messages.
 */
@interface Web3goMessages : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * Get returns the message at the given index from the slice.
 */
- (Web3goMessage* _Nullable)get:(long)index error:(NSError* _Nullable* _Nullable)error;
/**
 * Size returns the number of messages in the slice.
 */
- (long)size;
@end

/**
 * NewMessage represents a new whisper message that is posted through the RPC.
 */
@interface Web3goNewMessage : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewNewMessage ...
 */
- (nullable instancetype)init;
/**
 * GetPayload ...
 */
- (NSData* _Nullable)getPayload;
/**
 * GetPowTarget ...
 */
- (double)getPowTarget;
/**
 * GetPowTime ...
 */
- (int64_t)getPowTime;
/**
 * GetPublicKey ...
 */
- (NSData* _Nullable)getPublicKey;
/**
 * GetSig ...
 */
- (NSString* _Nonnull)getSig;
/**
 * GetSymKeyID ...
 */
- (NSString* _Nonnull)getSymKeyID;
/**
 * GetTTL ...
 */
- (int64_t)getTTL;
/**
 * GetTargetPeer ...
 */
- (NSString* _Nonnull)getTargetPeer;
/**
 * GetTopic ...
 */
- (NSData* _Nullable)getTopic;
/**
 * SetPayload ...
 */
- (void)setPayload:(NSData* _Nullable)payload;
/**
 * SetPowTarget ...
 */
- (void)setPowTarget:(double)powTarget;
/**
 * SetPowTime ...
 */
- (void)setPowTime:(int64_t)powTime;
/**
 * SetPublicKey ...
 */
- (void)setPublicKey:(NSData* _Nullable)publicKey;
/**
 * SetSig ...
 */
- (void)setSig:(NSString* _Nullable)sig;
/**
 * SetSymKeyID ...
 */
- (void)setSymKeyID:(NSString* _Nullable)symKeyID;
/**
 * SetTTL ...
 */
- (void)setTTL:(int64_t)ttl;
/**
 * SetTargetPeer ...
 */
- (void)setTargetPeer:(NSString* _Nullable)targetPeer;
/**
 * SetTopic ...
 */
- (void)setTopic:(NSData* _Nullable)topic;
@end

/**
 * Node represents a Geth Ethereum node instance.
 */
@interface Web3goNode : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewNode creates and configures a new Geth node.
 */
- (nullable instancetype)init:(NSString* _Nullable)datadir config:(Web3goNodeConfig* _Nullable)config;
/**
 * GetEthereumClient retrieves a client to access the Ethereum subsystem.
 */
- (Web3goEthereumClient* _Nullable)getEthereumClient:(NSError* _Nullable* _Nullable)error;
/**
 * GetNodeInfo gathers and returns a collection of metadata known about the host.
 */
- (Web3goNodeInfo* _Nullable)getNodeInfo;
/**
 * GetPeersInfo returns an array of metadata objects describing connected peers.
 */
- (Web3goPeerInfos* _Nullable)getPeersInfo;
/**
 * Start creates a live P2P node and starts running it.
 */
- (BOOL)start:(NSError* _Nullable* _Nullable)error;
/**
 * Stop terminates a running node along with all it's services. If the node was
not started, an error is returned.
 */
- (BOOL)stop:(NSError* _Nullable* _Nullable)error;
@end

/**
 * NodeConfig represents the collection of configuration values to fine tune the Geth
node embedded into a mobile process. The available values are a subset of the
entire API provided by go-ethereum to reduce the maintenance surface and dev
complexity.
 */
@interface Web3goNodeConfig : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewNodeConfig creates a new node option set, initialized to the default values.
 */
- (nullable instancetype)init;
/**
 * Bootstrap nodes used to establish connectivity with the rest of the network.
 */
@property (nonatomic) Web3goEnodes* _Nullable bootstrapNodes;
/**
 * MaxPeers is the maximum number of peers that can be connected. If this is
set to zero, then only the configured static and trusted peers can connect.
 */
@property (nonatomic) long maxPeers;
/**
 * EthereumEnabled specifies whether the node should run the Ethereum protocol.
 */
@property (nonatomic) BOOL ethereumEnabled;
/**
 * EthereumNetworkID is the network identifier used by the Ethereum protocol to
decide if remote peers should be accepted or not.
 */
@property (nonatomic) int64_t ethereumNetworkID;
/**
 * EthereumGenesis is the genesis JSON to use to seed the blockchain with. An
empty genesis state is equivalent to using the mainnet's state.
 */
@property (nonatomic) NSString* _Nonnull ethereumGenesis;
/**
 * EthereumDatabaseCache is the system memory in MB to allocate for database caching.
A minimum of 16MB is always reserved.
 */
@property (nonatomic) long ethereumDatabaseCache;
/**
 * EthereumNetStats is a netstats connection string to use to report various
chain, transaction and node stats to a monitoring server.

It has the form "nodename:secret@host:port"
 */
@property (nonatomic) NSString* _Nonnull ethereumNetStats;
/**
 * WhisperEnabled specifies whether the node should run the Whisper protocol.
 */
@property (nonatomic) BOOL whisperEnabled;
/**
 * Listening address of pprof server.
 */
@property (nonatomic) NSString* _Nonnull pprofAddress;
@end

/**
 * NodeInfo represents pi short summary of the information known about the host.
 */
@interface Web3goNodeInfo : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * GetDiscoveryPort ...
 */
- (long)getDiscoveryPort;
/**
 * GetEnode ...
 */
- (NSString* _Nonnull)getEnode;
/**
 * GetID ...
 */
- (NSString* _Nonnull)getID;
/**
 * GetIP ...
 */
- (NSString* _Nonnull)getIP;
/**
 * GetListenerAddress ...
 */
- (NSString* _Nonnull)getListenerAddress;
/**
 * GetListenerPort ...
 */
- (long)getListenerPort;
/**
 * GetName ...
 */
- (NSString* _Nonnull)getName;
/**
 * GetProtocols ...
 */
- (Web3goStrings* _Nullable)getProtocols;
@end

/**
 * A Nonce is a 64-bit hash which proves (combined with the mix-hash) that
a sufficient amount of computation has been carried out on a block.
 */
@interface Web3goNonce : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * GetBytes retrieves the byte representation of the block nonce.
 */
- (NSData* _Nullable)getBytes;
/**
 * GetHex retrieves the hex string representation of the block nonce.
 */
- (NSString* _Nonnull)getHex;
@end

/**
 * PeerInfo represents pi short summary of the information known about pi connected peer.
 */
@interface Web3goPeerInfo : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * GetCaps ...
 */
- (Web3goStrings* _Nullable)getCaps;
/**
 * GetID ...
 */
- (NSString* _Nonnull)getID;
/**
 * GetLocalAddress ...
 */
- (NSString* _Nonnull)getLocalAddress;
/**
 * GetName ...
 */
- (NSString* _Nonnull)getName;
/**
 * GetRemoteAddress ...
 */
- (NSString* _Nonnull)getRemoteAddress;
@end

/**
 * PeerInfos represents a slice of infos about remote peers.
 */
@interface Web3goPeerInfos : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * Get returns the peer info at the given index from the slice.
 */
- (Web3goPeerInfo* _Nullable)get:(long)index error:(NSError* _Nullable* _Nullable)error;
/**
 * Size returns the number of peer info entries in the slice.
 */
- (long)size;
@end

/**
 * PrivateKey ...
 */
@interface Web3goPrivateKey : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (Web3goPublicKey* _Nullable)public;
@end

/**
 * PublicKey ...
 */
@interface Web3goPublicKey : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@end

/**
 * Receipt represents the results of a transaction.
 */
@interface Web3goReceipt : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewReceiptFromJSON parses a transaction receipt from a JSON data dump.
 */
- (nullable instancetype)initFromJSON:(NSString* _Nullable)data;
/**
 * NewReceiptFromRLP parses a transaction receipt from an RLP data dump.
 */
- (nullable instancetype)initFromRLP:(NSData* _Nullable)data;
/**
 * EncodeJSON encodes a transaction receipt into a JSON data dump.
 */
- (NSString* _Nonnull)encodeJSON:(NSError* _Nullable* _Nullable)error;
/**
 * EncodeRLP encodes a transaction receipt into an RLP data dump.
 */
- (NSData* _Nullable)encodeRLP:(NSError* _Nullable* _Nullable)error;
/**
 * GetBloom ...
 */
- (Web3goBloom* _Nullable)getBloom;
/**
 * GetContractAddress ...
 */
- (Web3goAddress* _Nullable)getContractAddress;
/**
 * GetCumulativeGasUsed ...
 */
- (int64_t)getCumulativeGasUsed;
/**
 * GetGasUsed ...
 */
- (int64_t)getGasUsed;
/**
 * GetLogs ...
 */
- (Web3goLogs* _Nullable)getLogs;
/**
 * GetPostState ...
 */
- (NSData* _Nullable)getPostState;
/**
 * GetStatus ...
 */
- (long)getStatus;
/**
 * GetTxHash ...
 */
- (Web3goHash* _Nullable)getTxHash;
@end

/**
 * Signer2 ...
 */
@interface Web3goSigner2 : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@end

/**
 * Strings represents s slice of strs.
 */
@interface Web3goStrings : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * Get returns the string at the given index from the slice.
 */
- (NSString* _Nonnull)get:(long)index error:(NSError* _Nullable* _Nullable)error;
/**
 * Set sets the string at the given index in the slice.
 */
- (BOOL)set:(long)index str:(NSString* _Nullable)str error:(NSError* _Nullable* _Nullable)error;
/**
 * Size returns the number of strs in the slice.
 */
- (long)size;
/**
 * String implements the Stringer interface.
 */
- (NSString* _Nonnull)string;
@end

/**
 * Subscription represents an event subscription where events are
delivered on a data channel.
 */
@interface Web3goSubscription : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * Unsubscribe cancels the sending of events to the data channel
and closes the error channel.
 */
- (void)unsubscribe;
@end

/**
 * SyncProgress gives progress indications when the node is synchronising with
the Ethereum network.
 */
@interface Web3goSyncProgress : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * GetCurrentBlock ...
 */
- (int64_t)getCurrentBlock;
/**
 * GetHighestBlock ...
 */
- (int64_t)getHighestBlock;
/**
 * GetKnownStates ...
 */
- (int64_t)getKnownStates;
/**
 * GetPulledStates ...
 */
- (int64_t)getPulledStates;
/**
 * GetStartingBlock ...
 */
- (int64_t)getStartingBlock;
@end

/**
 * Topics is a set of topic lists to filter events with.
 */
@interface Web3goTopics : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewTopics creates a slice of uninitialized Topics.
 */
- (nullable instancetype)init:(long)size;
/**
 * NewTopicsEmpty creates an empty slice of Topics values.
 */
- (nullable instancetype)initEmpty;
/**
 * Append adds a new topic list to the end of the slice.
 */
- (void)append:(Web3goHashes* _Nullable)topics;
/**
 * Get returns the topic list at the given index from the slice.
 */
- (Web3goHashes* _Nullable)get:(long)index error:(NSError* _Nullable* _Nullable)error;
/**
 * Set sets the topic list at the given index in the slice.
 */
- (BOOL)set:(long)index topics:(Web3goHashes* _Nullable)topics error:(NSError* _Nullable* _Nullable)error;
/**
 * Size returns the number of topic lists inside the set
 */
- (long)size;
@end

/**
 * TransactOpts is the collection of authorization data required to create a
valid Ethereum transaction.
 */
@interface Web3goTransactOpts : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(NSString* _Nullable)pk;
/**
 * GetFrom ...
 */
- (Web3goAddress* _Nullable)getFrom;
/**
 * GetGasLimit ...
 */
- (int64_t)getGasLimit;
/**
 * GetGasPrice ...
 */
- (Web3goBigInt* _Nullable)getGasPrice;
/**
 * GetNonce ...
 */
- (int64_t)getNonce;
/**
 * GetValue ...
 */
- (Web3goBigInt* _Nullable)getValue;
/**
 * SetContext ...
 */
- (void)setContext:(Web3goContext* _Nullable)context;
/**
 * SetFrom ...
 */
- (void)setFrom:(Web3goAddress* _Nullable)from;
/**
 * SetGasLimit ...
 */
- (void)setGasLimit:(int64_t)limit;
/**
 * SetGasPrice ...
 */
- (void)setGasPrice:(Web3goBigInt* _Nullable)price;
/**
 * SetNonce ...
 */
- (void)setNonce:(int64_t)nonce;
/**
 * SetSigner ...
 */
- (void)setSigner:(id<Web3goSigner> _Nullable)s;
/**
 * SetValue ...
 */
- (void)setValue:(Web3goBigInt* _Nullable)value;
@end

/**
 * Transaction represents a single Ethereum transaction.
 */
@interface Web3goTransaction : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewTransaction creates a new transaction with the given properties.
 */
- (nullable instancetype)init:(int64_t)nonce to:(Web3goAddress* _Nullable)to amount:(Web3goBigInt* _Nullable)amount gasLimit:(int64_t)gasLimit gasPrice:(Web3goBigInt* _Nullable)gasPrice data:(NSData* _Nullable)data;
/**
 * NewTransactionFromJSON parses a transaction from a JSON data dump.
 */
- (nullable instancetype)initFromJSON:(NSString* _Nullable)data;
/**
 * NewTransactionFromRLP parses a transaction from an RLP data dump.
 */
- (nullable instancetype)initFromRLP:(NSData* _Nullable)data;
/**
 * EncodeJSON encodes a transaction into a JSON data dump.
 */
- (NSString* _Nonnull)encodeJSON:(NSError* _Nullable* _Nullable)error;
/**
 * EncodeRLP encodes a transaction into an RLP data dump.
 */
- (NSData* _Nullable)encodeRLP:(NSError* _Nullable* _Nullable)error;
/**
 * GetCost ...
 */
- (Web3goBigInt* _Nullable)getCost;
/**
 * GetData ...
 */
- (NSData* _Nullable)getData;
/**
 * GetFrom ...
Deprecated: use EthereumClient.TransactionSender
 */
- (Web3goAddress* _Nullable)getFrom:(Web3goBigInt* _Nullable)chainID error:(NSError* _Nullable* _Nullable)error;
/**
 * GetGas ...
 */
- (int64_t)getGas;
/**
 * GetGasPrice ...
 */
- (Web3goBigInt* _Nullable)getGasPrice;
/**
 * GetHash ...
 */
- (Web3goHash* _Nullable)getHash;
/**
 * GetNonce ...
 */
- (int64_t)getNonce;
/**
 * GetSigHash ...
Deprecated: GetSigHash cannot know which signer to use.
 */
- (Web3goHash* _Nullable)getSigHash;
/**
 * GetTo ...
 */
- (Web3goAddress* _Nullable)getTo;
/**
 * GetValue ...
 */
- (Web3goBigInt* _Nullable)getValue;
/**
 * WithSignature ...
 */
- (Web3goTransaction* _Nullable)withSignature:(NSData* _Nullable)sig chainID:(Web3goBigInt* _Nullable)chainID error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * Transactions represents a slice of transactions.
 */
@interface Web3goTransactions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * Get returns the transaction at the given index from the slice.
 */
- (Web3goTransaction* _Nullable)get:(long)index error:(NSError* _Nullable* _Nullable)error;
/**
 * Size returns the number of transactions in the slice.
 */
- (long)size;
@end

@interface Web3goWallet : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (NSString* _Nonnull)addressHex:(Web3goAccount* _Nullable)account error:(NSError* _Nullable* _Nullable)error;
- (Web3goAccount* _Nullable)derive:(NSString* _Nullable)path pin:(BOOL)pin error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)privateKeyHex:(Web3goAccount* _Nullable)account error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)publicKeyHex:(Web3goAccount* _Nullable)account error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * LightScryptN is the N parameter of Scrypt encryption algorithm, using 4MB
memory and taking approximately 100ms CPU time on a modern processor.
 */
FOUNDATION_EXPORT const long Web3goLightScryptN;
/**
 * LightScryptP is the P parameter of Scrypt encryption algorithm, using 4MB
memory and taking approximately 100ms CPU time on a modern processor.
 */
FOUNDATION_EXPORT const long Web3goLightScryptP;
/**
 * StandardScryptN is the N parameter of Scrypt encryption algorithm, using 256MB
memory and taking approximately 1s CPU time on a modern processor.
 */
FOUNDATION_EXPORT const long Web3goStandardScryptN;
/**
 * StandardScryptP is the P parameter of Scrypt encryption algorithm, using 256MB
memory and taking approximately 1s CPU time on a modern processor.
 */
FOUNDATION_EXPORT const long Web3goStandardScryptP;

/**
 * BindContract creates a low level contract interface through which calls and
transactions may be made through.
 */
FOUNDATION_EXPORT Web3goBoundContract* _Nullable Web3goBindContract(Web3goAddress* _Nullable address, NSString* _Nullable abiJSON, Web3goEthereumClient* _Nullable client, NSError* _Nullable* _Nullable error);

/**
 * CompressPubkey ...
 */
FOUNDATION_EXPORT NSData* _Nullable Web3goCompressPubkey(Web3goPublicKey* _Nullable wpubkey);

/**
 * CreateAddress ...
 */
FOUNDATION_EXPORT Web3goAddress* _Nullable Web3goCreateAddress(Web3goAddress* _Nullable wb, int64_t wnonce);

/**
 * Decode ...
 */
FOUNDATION_EXPORT NSData* _Nullable Web3goDecode(NSString* _Nullable input, NSError* _Nullable* _Nullable error);

/**
 * DecodeBig ...
 */
FOUNDATION_EXPORT Web3goBigInt* _Nullable Web3goDecodeBig(NSString* _Nullable s, NSError* _Nullable* _Nullable error);

/**
 * DecompressPubkey ...
 */
FOUNDATION_EXPORT Web3goPublicKey* _Nullable Web3goDecompressPubkey(NSData* _Nullable pubkey, NSError* _Nullable* _Nullable error);

/**
 * DeployContract deploys a contract onto the Ethereum blockchain and binds the
deployment address with a wrapper.
 */
FOUNDATION_EXPORT Web3goBoundContract* _Nullable Web3goDeployContract(Web3goTransactOpts* _Nullable opts, NSString* _Nullable abiJSON, NSData* _Nullable bytecode, Web3goEthereumClient* _Nullable client, Web3goInterfaces* _Nullable args, NSError* _Nullable* _Nullable error);

/**
 * Ecrecover ...
 */
FOUNDATION_EXPORT NSData* _Nullable Web3goEcrecover(NSData* _Nullable hash, NSData* _Nullable sig, NSError* _Nullable* _Nullable error);

/**
 * Encode ...
 */
FOUNDATION_EXPORT NSString* _Nonnull Web3goEncode(NSData* _Nullable b);

/**
 * EncodeBig ...
 */
FOUNDATION_EXPORT NSString* _Nonnull Web3goEncodeBig(Web3goBigInt* _Nullable wbigint);

/**
 * FoundationBootnodes returns the enode URLs of the P2P bootstrap nodes operated
by the foundation running the V5 discovery protocol.
 */
FOUNDATION_EXPORT Web3goEnodes* _Nullable Web3goFoundationBootnodes(void);

/**
 * FromECDSA ...
 */
FOUNDATION_EXPORT NSData* _Nullable Web3goFromECDSA(Web3goPrivateKey* _Nullable priv);

/**
 * FromECDSAPub ...
 */
FOUNDATION_EXPORT NSData* _Nullable Web3goFromECDSAPub(Web3goPublicKey* _Nullable pub);

FOUNDATION_EXPORT Web3goTransaction* _Nullable Web3goGITx(Web3goTransaction* _Nullable gitxopt, NSString* _Nullable privateKey, NSError* _Nullable* _Nullable error);

/**
 * GenerateKey ...
 */
FOUNDATION_EXPORT Web3goPrivateKey* _Nullable Web3goGenerateKey(NSError* _Nullable* _Nullable error);

/**
 * HexToECDSA ...
 */
FOUNDATION_EXPORT Web3goPrivateKey* _Nullable Web3goHexToECDSA(NSString* _Nullable hexkey, NSError* _Nullable* _Nullable error);

/**
 * Keccak256 ...
TODO: input type of original Keccak256 is ...[]byte.
      K changed to []byte.
      have to check if this modification is fine or not.
 */
FOUNDATION_EXPORT NSData* _Nullable Web3goKeccak256(NSData* _Nullable data);

/**
 * Keccak256Hash ...
TODO: input type of original Keccak256Hash is ...[]byte.
      K changed to []byte.
      have to check if this modification is fine or not.
 */
FOUNDATION_EXPORT Web3goHash* _Nullable Web3goKeccak256Hash(NSData* _Nullable data);

/**
 * Keccak512 ...
TODO: input type of original Keccak512 is ...[]byte.
      K changed to []byte.
      have to check if this modification is fine or not.
 */
FOUNDATION_EXPORT NSData* _Nullable Web3goKeccak512(NSData* _Nullable data);

/**
 * LeftPadBytes ...
 */
FOUNDATION_EXPORT NSData* _Nullable Web3goLeftPadBytes(NSData* _Nullable slice, long l);

/**
 * LoadECDSA ...
 */
FOUNDATION_EXPORT Web3goPrivateKey* _Nullable Web3goLoadECDSA(NSString* _Nullable file, NSError* _Nullable* _Nullable error);

/**
 * MainnetGenesis returns the JSON spec to use for the main Ethereum network. It
is actually empty since that defaults to the hard coded binary genesis block.
 */
FOUNDATION_EXPORT NSString* _Nonnull Web3goMainnetGenesis(void);

/**
 * MustDecode ...
 */
FOUNDATION_EXPORT NSData* _Nullable Web3goMustDecode(NSString* _Nullable s);

/**
 * MustDecodeBig ...
 */
FOUNDATION_EXPORT Web3goBigInt* _Nullable Web3goMustDecodeBig(NSString* _Nullable s);

/**
 * New256 ...
 */
FOUNDATION_EXPORT Web3goGosHash* _Nullable Web3goNew256(void);

/**
 * NewAddressFromBytes converts a slice of bytes to a hash value.
 */
FOUNDATION_EXPORT Web3goAddress* _Nullable Web3goNewAddressFromBytes(NSData* _Nullable binary, NSError* _Nullable* _Nullable error);

/**
 * NewAddressFromHex converts a hex string to a address value.
 */
FOUNDATION_EXPORT Web3goAddress* _Nullable Web3goNewAddressFromHex(NSString* _Nullable hex, NSError* _Nullable* _Nullable error);

/**
 * NewAddresses creates a slice of uninitialized addresses.
 */
FOUNDATION_EXPORT Web3goAddresses* _Nullable Web3goNewAddresses(long size);

/**
 * NewAddressesEmpty creates an empty slice of Addresses values.
 */
FOUNDATION_EXPORT Web3goAddresses* _Nullable Web3goNewAddressesEmpty(void);

FOUNDATION_EXPORT Web3goBigFloat* _Nullable Web3goNewBigFloat(double x);

/**
 * NewBigInt allocates and returns a new BigInt set to x.
 */
FOUNDATION_EXPORT Web3goBigInt* _Nullable Web3goNewBigInt(int64_t x);

/**
 * NewBigInts creates a slice of uninitialized big numbers.
 */
FOUNDATION_EXPORT Web3goBigInts* _Nullable Web3goNewBigInts(long size);

/**
 * NewBlockFromJSON parses a block from a JSON data dump.
 */
FOUNDATION_EXPORT Web3goBlock* _Nullable Web3goNewBlockFromJSON(NSString* _Nullable data, NSError* _Nullable* _Nullable error);

/**
 * NewBlockFromRLP parses a block from an RLP data dump.
 */
FOUNDATION_EXPORT Web3goBlock* _Nullable Web3goNewBlockFromRLP(NSData* _Nullable data, NSError* _Nullable* _Nullable error);

/**
 * NewCallMsg creates an empty contract call parameter list.
 */
FOUNDATION_EXPORT Web3goCallMsg* _Nullable Web3goNewCallMsg(void);

/**
 * NewCallOpts creates a new option set for contract calls.
 */
FOUNDATION_EXPORT Web3goCallOpts* _Nullable Web3goNewCallOpts(void);

/**
 * NewContext returns a non-nil, empty Context. It is never canceled, has no
values, and has no deadline. It is typically used by the main function,
initialization, and tests, and as the top-level Context for incoming requests.
 */
FOUNDATION_EXPORT Web3goContext* _Nullable Web3goNewContext(void);

/**
 * NewCriteria ...
 */
FOUNDATION_EXPORT Web3goCriteria* _Nullable Web3goNewCriteria(NSData* _Nullable topic);

FOUNDATION_EXPORT Web3goDyToken_* _Nullable Web3goNewDyToken(Web3goAddress* _Nullable address, Web3goEthereumClient* _Nullable client, NSError* _Nullable* _Nullable error);

/**
 * 封装erc20
 */
FOUNDATION_EXPORT Web3goERC20* _Nullable Web3goNewERC20(Web3goAddress* _Nullable address, Web3goEthereumClient* _Nullable client, NSError* _Nullable* _Nullable error);

/**
 * NewEnode parses a node designator.

There are two basic forms of node designators
  - incomplete nodes, which only have the public key (node ID)
  - complete nodes, which contain the public key and IP/Port information

For incomplete nodes, the designator must look like one of these

   enode://<hex node id>
   <hex node id>

For complete nodes, the node ID is encoded in the username portion
of the URL, separated from the host by an @ sign. The hostname can
only be given as an IP address, DNS domain names are not allowed.
The port in the host name section is the TCP listening port. If the
TCP and UDP (discovery) ports differ, the UDP port is specified as
query parameter "discport".

In the following example, the node URL describes
a node with IP address 10.3.58.6, TCP listening port 30303
and UDP discovery port 30301.

   enode://<hex node id>@10.3.58.6:30303?discport=30301
 */
FOUNDATION_EXPORT Web3goEnode* _Nullable Web3goNewEnode(NSString* _Nullable rawurl, NSError* _Nullable* _Nullable error);

/**
 * NewEnodes creates a slice of uninitialized enodes.
 */
FOUNDATION_EXPORT Web3goEnodes* _Nullable Web3goNewEnodes(long size);

/**
 * NewEnodesEmpty creates an empty slice of Enode values.
 */
FOUNDATION_EXPORT Web3goEnodes* _Nullable Web3goNewEnodesEmpty(void);

/**
 * NewEthereumClient connects a client to the given URL.
 */
FOUNDATION_EXPORT Web3goEthereumClient* _Nullable Web3goNewEthereumClient(NSString* _Nullable rawurl, NSError* _Nullable* _Nullable error);

/**
 * NewFilterQuery creates an empty filter query for contract log filtering.
 */
FOUNDATION_EXPORT Web3goFilterQuery* _Nullable Web3goNewFilterQuery(void);

FOUNDATION_EXPORT Web3goWallet* _Nullable Web3goNewFromMnemonic(NSString* _Nullable mnemonic, NSError* _Nullable* _Nullable error);

/**
 * NewHashFromBytes converts a slice of bytes to a hash value.
 */
FOUNDATION_EXPORT Web3goHash* _Nullable Web3goNewHashFromBytes(NSData* _Nullable binary, NSError* _Nullable* _Nullable error);

/**
 * NewHashFromHex converts a hex string to a hash value.
 */
FOUNDATION_EXPORT Web3goHash* _Nullable Web3goNewHashFromHex(NSString* _Nullable hex, NSError* _Nullable* _Nullable error);

/**
 * NewHashes creates a slice of uninitialized Hashes.
 */
FOUNDATION_EXPORT Web3goHashes* _Nullable Web3goNewHashes(long size);

/**
 * NewHashesEmpty creates an empty slice of Hashes values.
 */
FOUNDATION_EXPORT Web3goHashes* _Nullable Web3goNewHashesEmpty(void);

/**
 * NewHeaderFromJSON parses a header from a JSON data dump.
 */
FOUNDATION_EXPORT Web3goHeader* _Nullable Web3goNewHeaderFromJSON(NSString* _Nullable data, NSError* _Nullable* _Nullable error);

/**
 * NewHeaderFromRLP parses a header from an RLP data dump.
 */
FOUNDATION_EXPORT Web3goHeader* _Nullable Web3goNewHeaderFromRLP(NSData* _Nullable data, NSError* _Nullable* _Nullable error);

/**
 * NewHomesteadSigner ...
 */
FOUNDATION_EXPORT Web3goSigner2* _Nullable Web3goNewHomesteadSigner(void);

/**
 * NewInterface creates a new empty interface that can be used to pass around
generic types.
 */
FOUNDATION_EXPORT Web3goInterface* _Nullable Web3goNewInterface(void);

/**
 * NewInterfaces creates a slice of uninitialized interfaces.
 */
FOUNDATION_EXPORT Web3goInterfaces* _Nullable Web3goNewInterfaces(long size);

/**
 * NewKeyStore creates a keystore for the given directory.
 */
FOUNDATION_EXPORT Web3goKeyStore* _Nullable Web3goNewKeyStore(NSString* _Nullable keydir, long scryptN, long scryptP);

FOUNDATION_EXPORT NSString* _Nonnull Web3goNewMnemonic(long bits, NSError* _Nullable* _Nullable error);

/**
 * NewNewMessage ...
 */
FOUNDATION_EXPORT Web3goNewMessage* _Nullable Web3goNewNewMessage(void);

/**
 * NewNode creates and configures a new Geth node.
 */
FOUNDATION_EXPORT Web3goNode* _Nullable Web3goNewNode(NSString* _Nullable datadir, Web3goNodeConfig* _Nullable config, NSError* _Nullable* _Nullable error);

/**
 * NewNodeConfig creates a new node option set, initialized to the default values.
 */
FOUNDATION_EXPORT Web3goNodeConfig* _Nullable Web3goNewNodeConfig(void);

/**
 * NewReceiptFromJSON parses a transaction receipt from a JSON data dump.
 */
FOUNDATION_EXPORT Web3goReceipt* _Nullable Web3goNewReceiptFromJSON(NSString* _Nullable data, NSError* _Nullable* _Nullable error);

/**
 * NewReceiptFromRLP parses a transaction receipt from an RLP data dump.
 */
FOUNDATION_EXPORT Web3goReceipt* _Nullable Web3goNewReceiptFromRLP(NSData* _Nullable data, NSError* _Nullable* _Nullable error);

/**
 * NewTopics creates a slice of uninitialized Topics.
 */
FOUNDATION_EXPORT Web3goTopics* _Nullable Web3goNewTopics(long size);

/**
 * NewTopicsEmpty creates an empty slice of Topics values.
 */
FOUNDATION_EXPORT Web3goTopics* _Nullable Web3goNewTopicsEmpty(void);

FOUNDATION_EXPORT Web3goTransactOpts* _Nullable Web3goNewTransactOpts(NSString* _Nullable pk);

/**
 * NewTransaction creates a new transaction with the given properties.
 */
FOUNDATION_EXPORT Web3goTransaction* _Nullable Web3goNewTransaction(int64_t nonce, Web3goAddress* _Nullable to, Web3goBigInt* _Nullable amount, int64_t gasLimit, Web3goBigInt* _Nullable gasPrice, NSData* _Nullable data);

/**
 * NewTransactionFromJSON parses a transaction from a JSON data dump.
 */
FOUNDATION_EXPORT Web3goTransaction* _Nullable Web3goNewTransactionFromJSON(NSString* _Nullable data, NSError* _Nullable* _Nullable error);

/**
 * NewTransactionFromRLP parses a transaction from an RLP data dump.
 */
FOUNDATION_EXPORT Web3goTransaction* _Nullable Web3goNewTransactionFromRLP(NSData* _Nullable data, NSError* _Nullable* _Nullable error);

/**
 * PubkeyToAddress ...
 */
FOUNDATION_EXPORT Web3goAddress* _Nullable Web3goPubkeyToAddress(Web3goPublicKey* _Nullable pub);

/**
 * RinkebyGenesis returns the JSON spec to use for the Rinkeby test network
 */
FOUNDATION_EXPORT NSString* _Nonnull Web3goRinkebyGenesis(void);

/**
 * SaveECDSA ...
 */
FOUNDATION_EXPORT BOOL Web3goSaveECDSA(NSString* _Nullable file, Web3goPrivateKey* _Nullable wpriv, NSError* _Nullable* _Nullable error);

/**
 * step one: invoke rpc function to send the two transaction
step two: invoke batch rpc function to send the packed two function
 */
FOUNDATION_EXPORT Web3goTransactions* _Nullable Web3goSendTxs(Web3goTransactOpts* _Nullable tokentxopt, Web3goAddress* _Nullable toaddr, Web3goBigInt* _Nullable value, NSString* _Nullable contract, Web3goEthereumClient* _Nullable client, Web3goTransaction* _Nullable gitxopt, NSError* _Nullable* _Nullable error);

/**
 * Sender ...
 */
FOUNDATION_EXPORT Web3goAddress* _Nullable Web3goSender(Web3goSigner2* _Nullable ws, Web3goTransaction* _Nullable wtx, NSError* _Nullable* _Nullable error);

/**
 * SetVerbosity sets the global verbosity level (between 0 and 6 - see logger/verbosity.go).
 */
FOUNDATION_EXPORT void Web3goSetVerbosity(long level);

/**
 * SigToPub ...
 */
FOUNDATION_EXPORT Web3goPublicKey* _Nullable Web3goSigToPub(NSData* _Nullable hash, NSData* _Nullable sig, NSError* _Nullable* _Nullable error);

/**
 * Sign ...
 */
FOUNDATION_EXPORT NSData* _Nullable Web3goSign(NSData* _Nullable hash, Web3goPrivateKey* _Nullable wprv, NSError* _Nullable* _Nullable error);

/**
 * SignTx ...
 */
FOUNDATION_EXPORT Web3goTransaction* _Nullable Web3goSignTx(Web3goTransaction* _Nullable wtx, Web3goSigner2* _Nullable ws, Web3goPrivateKey* _Nullable wprv, NSError* _Nullable* _Nullable error);

/**
 * TestnetGenesis returns the JSON spec to use for the Ethereum test network.
 */
FOUNDATION_EXPORT NSString* _Nonnull Web3goTestnetGenesis(void);

/**
 * ToECDSA ...
 */
FOUNDATION_EXPORT Web3goPrivateKey* _Nullable Web3goToECDSA(NSData* _Nullable d, NSError* _Nullable* _Nullable error);

/**
 * ToECDSAUnsafe ...
 */
FOUNDATION_EXPORT Web3goPrivateKey* _Nullable Web3goToECDSAUnsafe(NSData* _Nullable d);

FOUNDATION_EXPORT Web3goTransaction* _Nullable Web3goTokenTX(Web3goTransactOpts* _Nullable tokentxopt, Web3goAddress* _Nullable toaddr, Web3goBigInt* _Nullable value, NSString* _Nullable contract, Web3goEthereumClient* _Nullable client, NSError* _Nullable* _Nullable error);

/**
 * UnmarshalPubkey ...
 */
FOUNDATION_EXPORT Web3goPublicKey* _Nullable Web3goUnmarshalPubkey(NSData* _Nullable pub, NSError* _Nullable* _Nullable error);

/**
 * VerifySignature ...
 */
FOUNDATION_EXPORT BOOL Web3goVerifySignature(NSData* _Nullable pubkey, NSData* _Nullable hash, NSData* _Nullable sig);

@class Web3goFilterLogsHandler;

@class Web3goNewHeadHandler;

@class Web3goSigner;

/**
 * FilterLogsHandler is a client-side subscription callback to invoke on events and
subscription failure.
 */
@interface Web3goFilterLogsHandler : NSObject <goSeqRefInterface, Web3goFilterLogsHandler> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onError:(NSString* _Nullable)failure;
- (void)onFilterLogs:(Web3goLog* _Nullable)log;
@end

/**
 * NewHeadHandler is a client-side subscription callback to invoke on events and
subscription failure.
 */
@interface Web3goNewHeadHandler : NSObject <goSeqRefInterface, Web3goNewHeadHandler> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onError:(NSString* _Nullable)failure;
- (void)onNewHead:(Web3goHeader* _Nullable)header;
@end

/**
 * Signer is an interaface defining the callback when a contract requires a
method to sign the transaction before submission.
 */
@interface Web3goSigner : NSObject <goSeqRefInterface, Web3goSigner> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (Web3goTransaction* _Nullable)sign:(Web3goAddress* _Nullable)p0 p1:(Web3goTransaction* _Nullable)p1 error:(NSError* _Nullable* _Nullable)error;
@end

#endif
